name: '[CI/CD] CI Pipeline'
on: # Test pull requests and any push to main.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: # Force read permissions
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - id: npm-ci
        name: Clean install
        run: npm ci
      - name: Linter
        run: npm run lint
      - name: Tests
        # Run tests if linter fails
        if: always() && steps.npm-ci.outcome == 'success'
        run: npm run test-ci